language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
install:
  - pip install --user -r requirements.txt
before_script:

script:
  - python manage.py runserver 127.0.0.1:8000